CREATE SCHEMA IF NOT EXISTS Wallet;

CREATE TABLE IF NOT EXISTS Wallet."Address" (
    "Id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "Street" VARCHAR(255) NOT NULL,
    "Number" INTEGER NOT NULL,
    "City" VARCHAR(100) NOT NULL,
    "Country" VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Wallet."User" (
    "Id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "AddressId" INTEGER NOT NULL,
    "Name" VARCHAR(255) NOT NULL,
    "Birthday" DATE NOT NULL,
    "Email" VARCHAR(255) NOT NULL,
    "CreatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_user_address FOREIGN KEY ("AddressId")
        REFERENCES wallet."Address"("Id") ON DELETE RESTRICT,

    CONSTRAINT uk_user_email UNIQUE ("Email")
);

CREATE INDEX IF NOT EXISTS idx_user_name ON Wallet."User" ("Name");
CREATE INDEX IF NOT EXISTS idx_user_address_id ON Wallet."User" ("AddressId");